//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\PuzzleServer\\PicturePuzzleService\\HostWinform\\bin\\Debug\\concat_yolov560_m_640_" +
            "4_1031.engine")]
        public string EnginePath {
            get {
                return ((string)(this["EnginePath"]));
            }
            set {
                this["EnginePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\sourceETL\\Upload\\")]
        public string UploadPath {
            get {
                return ((string)(this["UploadPath"]));
            }
            set {
                this["UploadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\sourceETL\\sourceFolders\\source\\")]
        public string PuzzlePath {
            get {
                return ((string)(this["PuzzlePath"]));
            }
            set {
                this["PuzzlePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\PuzzleService\\Bak\\")]
        public string BakPath {
            get {
                return ((string)(this["BakPath"]));
            }
            set {
                this["BakPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\PuzzleService\\Zip\\{0}.zip")]
        public string ZipPath {
            get {
                return ((string)(this["ZipPath"]));
            }
            set {
                this["ZipPath"] = value;
            }
        }
    }
}
